# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0004_auto_20170926_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='storiespage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
