# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0007_auto_20171003_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='storiespage',
            name='authors',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
