# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('blacktail', '0008_storiespage_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoriesPageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='storiespage',
            name='dossier',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='storiespage',
            name='format',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='storiespagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blacktail.StoriesPage'),
        ),
        migrations.AddField(
            model_name='storiespagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_storiespagetag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='storiespage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blacktail.StoriesPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
