# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-18 09:00
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0011_auto_20171017_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storiespage',
            old_name='body',
            new_name='body_blocks',
        ),
        migrations.AddField(
            model_name='storiespage',
            name='body_richtext',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
