# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 14:40
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0023_auto_20171113_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storiesauthors',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_authors', to='blacktail.StoriesPage'),
        ),
    ]
