# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('blacktail', '0032_auto_20171122_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storytype',
            name='icon',
        ),
        migrations.AddField(
            model_name='storytype',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
