# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0034_storiespage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storiespage',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
