# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 11:57
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0043_auto_20180101_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(related_name='blogs', to='blacktail.Author'),
        ),
    ]
