# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0044_blogpost_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='template',
            new_name='post_template',
        ),
    ]
