# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0045_auto_20180109_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='intro',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
