# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-15 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0051_auto_20180502_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='date',
        ),
    ]
