# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-15 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0052_remove_story_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='date',
        ),
    ]
