# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-15 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0053_remove_blogpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='skip_home',
            field=models.BooleanField(default=False),
        ),
    ]
