# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-17 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0054_story_skip_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='skip_home',
            field=models.BooleanField(default=None),
        ),
    ]
