# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-17 12:14
from __future__ import unicode_literals

import blacktail.models.streamfield
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0058_storyrelatedlinks_storyrelatedpages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='body',
            field=wagtail.core.fields.StreamField((('subheadline', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('h2', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('h3', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('h4', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('intro', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('aligned_image', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock()), ('alignment', blacktail.models.streamfield.ImageFormatChoiceBlock())), icon='image', label='Aligned image')), ('aligned_html', wagtail.core.blocks.StructBlock((('html', wagtail.core.blocks.RawHTMLBlock()), ('alignment', blacktail.models.streamfield.HTMLAlignmentChoiceBlock())), icon='code', label='Raw HTML')), ('embed', wagtail.embeds.blocks.EmbedBlock(help_text='URL for media to embed')), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse'))), blank=True),
        ),
    ]
