# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0062_auto_20180518_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='translation_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tranlations', to='blacktail.Story'),
        ),
        migrations.AddField(
            model_name='story',
            name='translation_language',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
