# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0063_auto_20180518_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='translation_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='blacktail.Story'),
        ),
    ]
