# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-09 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0065_auto_20180909_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page', to='blacktail.StoryDossier'),
        ),
    ]
