# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-10 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0068_auto_20180910_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoriesFolderTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='storiesfolder',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blacktail.StoriesFolderTemplate'),
        ),
    ]
