# Generated by Django 2.0.9 on 2018-10-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0071_auto_20181009_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='storiesfolder',
            name='summary',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
