# Generated by Django 2.0.9 on 2018-10-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0072_storiesfolder_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='storiesfolder',
            name='hide_title',
            field=models.BooleanField(default=False),
        ),
    ]
