# Generated by Django 2.0.9 on 2018-10-21 12:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations

authors = {}


def forward_1(apps, schema_editor):
    Story = apps.get_model('blacktail', 'Story')
    for story in Story.objects.all():
        authors[story.pk] = [a.pk for a in story.authors.all()]
    print(authors)


def forward_2(apps, schema_editor):
    Story = apps.get_model('blacktail', 'Story')
    for story in Story.objects.all():
        author_ids = authors.get(story.pk)
        if author_ids:
            story.author_ids = author_ids
            story.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0073_storiesfolder_hide_title'),
    ]

    operations = [
        migrations.RunPython(forward_1),
        migrations.RemoveField(
            model_name='story',
            name='authors',
        ),
        migrations.AddField(
            model_name='story',
            name='author_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.RunPython(forward_2),
    ]
