# Generated by Django 2.0.9 on 2018-10-30 20:32

import json
from django.db import migrations


def forward(apps, schema_editor):
    Story = apps.get_model('blacktail', 'Story')
    for story in Story.objects.all():
        for rev in story.revisions.all():
            content = json.loads(rev.content_json)
            body = json.loads(content['body'])
            changed = False
            for item in body:
                if item['type'] == 'image_gallery':
                    body.remove(item)
                    changed = True
            if changed:
                content['body'] = json.dumps(body)
                rev.content_json = json.dumps(content)
                rev.save()
                print(story, rev)


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0075_auto_20181029_1845'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
