# Generated by Django 2.0.9 on 2018-11-02 13:38

import blacktail.models.streamfield
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0076_auto_20181030_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='body',
            field=wagtail.core.fields.StreamField([('subheadline', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('embedded_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('clickable', wagtail.core.blocks.BooleanBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('h2', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('h3', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('h4', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('intro', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.TextBlock(required=False)), ('alignment', blacktail.models.streamfield.ImageFormatChoiceBlock())], icon='image', label='Image')), ('aligned_html', wagtail.core.blocks.StructBlock([('html', wagtail.core.blocks.RawHTMLBlock()), ('alignment', blacktail.models.streamfield.HTMLAlignmentChoiceBlock())], icon='code', label='Raw HTML')), ('embed', wagtail.embeds.blocks.EmbedBlock(help_text='URL for media to embed')), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse')), ('image_gallery', blacktail.models.streamfield.ImageGalleryBlock(blacktail.models.streamfield.ImageGalleryItemBlock))], blank=True),
        ),
    ]
