# Generated by Django 2.0.9 on 2018-11-02 14:05

from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    Story = apps.get_model('blacktail', 'Story')
    StoryTemplate = apps.get_model('blacktail', 'StoryTemplate')
    template = StoryTemplate.objects.create(name="ivory")
    Story.objects.filter(template__isnull=True).update(template=template)


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0077_auto_20181102_1338'),
    ]

    operations = [
        migrations.RunPython(forward),
        migrations.AlterField(
            model_name='story',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blacktail.StoryTemplate'),
        ),
        migrations.AlterField(
            model_name='storiesfolder',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blacktail.StoriesFolderTemplate'),
        ),
    ]
