# Generated by Django 2.1.7 on 2019-09-11 14:26

"""
Set up the Toxic Valley template
"""

from django.db import migrations


def up(apps, schema_editor):
    StoryTemplate = apps.get_model('blacktail', 'StoryTemplate')
    StoryTemplate.objects.create(name='toxic')


def down(apps, schema_editor):
    StoryTemplate = apps.get_model('blacktail', 'StoryTemplate')
    toxic = StoryTemplate.objects.get(name='toxic')
    toxic.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blacktail', '0079_auto_20181104_1726'),
    ]

    operations = [
        migrations.RunPython(up, down),
    ]
