web:
  build: .
  dockerfile: Dockerfile
  command: python manage.py runserver 0.0.0.0:80
  volumes:
    - ./:/app
  links:
   - postgres
   - elasticsearch
  ports:
   - "80:80"
  environment:
    - DEBUG=True
    - DEV=True
    - DATABASE_URL=postgres://postgres:@postgres:5432/postgres
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - SECRET_KEY=notasecretreplaceme
postgres:
  image: postgres
  ports:
   - "5432:5432"
elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
