# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-30 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('blog', '0015_homepage_staticpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='page',
        ),
        migrations.RemoveField(
            model_name='advertplacement',
            name='advert',
        ),
        migrations.RemoveField(
            model_name='advertplacement',
            name='page',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.StoriesPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.DeleteModel(
            name='Advert',
        ),
        migrations.DeleteModel(
            name='AdvertPlacement',
        ),
    ]
