# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20171113_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='tags',
        ),
    ]
