# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 13:59
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_blogpage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storiesauthors',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_authors', to='blog.StoriesPage'),
        ),
    ]
