# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20171113_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storiesauthors',
            name='image',
        ),
        migrations.RemoveField(
            model_name='storiesauthors',
            name='page',
        ),
        migrations.DeleteModel(
            name='StoriesAuthors',
        ),
    ]
