# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_storiespage_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storiespage',
            name='authors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='blog.Author'),
        ),
        migrations.AlterField(
            model_name='storiespage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories_related', to='wagtailimages.Image'),
        ),
    ]
