# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20171113_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storiespage',
            name='authors',
        ),
        migrations.AddField(
            model_name='storiespage',
            name='authors',
            field=models.ManyToManyField(to='blog.Author'),
        ),
    ]
