# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:22
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20171113_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storiespage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(related_name='stories', to='blog.Author'),
        ),
    ]
