# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20171113_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='intro',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='author',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, max_length=254),
        ),
    ]
