# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_staticpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
